name: tech_nebrios_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  intl: ^0.17.0
  
  http: ^1.1.0 # Comunicación HTTP
  dio: ^5.3.2  # Cliente HTTP más avanzado
  cached_network_image: ^3.2.3 # Cargar imágenes

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
